from utils.database import db


class Employee(db.Model):
    """
    Employee model: This class represents the 'Employee' table in the database.

    Attributes:
        employee_id (int): Primary key, unique identifier for each employee.
        name (str): Name of the employee.
        email (str): Unique email address of the employee.
        phone (str): Phone number of the employee (optional).
        role (str): Role of the employee (e.g., 'mechanic', 'manager'). Default is 'mechanic'.
        hired_date (date): Date when the employee was hired.
        created_at (datetime): Timestamp indicating when the record was created. Auto-generated by the database.
    """
    # Primary key column
    employee_id = db.Column(db.Integer, primary_key=True)

    # Employee details
    name = db.Column(db.String(80), nullable=False)  # Employee name (mandatory)
    email = db.Column(db.String(200), unique=True, nullable=False)  # Unique email address (mandatory)
    phone = db.Column(db.String(20))  # Phone number (optional)

    # Role and employment information
    role = db.Column(db.String(20), nullable=False, default='mechanic')  # Role with a default value of 'mechanic'
    hired_date = db.Column(db.Date, nullable=False)  # Mandatory hire date

    # Audit information
    created_at = db.Column(db.DateTime, server_default=db.func.now())  # Timestamp for when the record was created

    def __repr__(self):
        """
        String representation of the Employee object.

        :return: A string showing the employee's name.
        """
        return f"<Employee {self.name}>"